### ISSUE TITLE
Warning about debug kernel in dmesg

### ISSUE THREAD

**Issue by BenediktCyranka** [varigit/DART-SD410-kernel#1]
Looking in dmesg after a normal boot shows this message.
With the 19.01 branch and tested on commit 9ca0f8f.

**********************************************************
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**                                                      **
** trace_printk() being used. Allocating extra memory.  **
**                                                      **
** This means that this is a DEBUG kernel and it is     **
** unsafe for production use.                           **
**                                                      **
** If you see this message and you are not debugging    **
** the kernel, report this immediately to your vendor!  **
**                                                      **
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**********************************************************

**Comment by leonid-s** [comment]
I do not see it in my log

**Comment by BenediktCyranka** [comment]
This is strange. I do a clean build without any patches from my side.
But this message comes on every boot.
Any idears?

**Comment by BenediktCyranka** [comment]
After I disabled in kernel menuconfig the printk support the message is not shown anymore.
